version: "0.1"

services:
  app:
    image: 792520190064.dkr.ecr.ap-south-1.amazonaws.com/concierge/backend:01
    container_name: my-app
    restart: unless-stopped

    ports:
      - "8000:8000"

    env_file:
      - .env
